{% set name = "azure-core" %}
{% set version = "1.36.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/azure-core/azure_core-1.36.0.tar.gz
  sha256: 22e5605e6d0bf1d229726af56d9e92bc37b6e726b141a18be0b4d424131741b7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - requests >=2.21.0
    - six >=1.11.0
    - typing-extensions >=4.6.0
    - typing_extensions >=4.6.0
  run_constrained:
    - aiohttp >=3.0
    - opentelemetry-api >=1.26,<2.dev0

# azure-core has a tests but all of them require running test server which is not started here.
test:
  imports:
    - azure.core
    - azure.core.utils
    - azure.core.rest
    - azure.core.tracing
    - azure.core.tracing
    - azure.core.polling
    - azure.core.pipeline
    - azure.core.pipeline.policies
    - azure.core.pipeline.transport
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
  doc_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
  summary: Microsoft Azure Core Library for Python
  description: |
    Azure core provides shared exceptions and modules for Python SDK client libraries.
    These libraries follow the Azure SDK Design Guidelines for Python.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
