{% set name = "azure-core" %}
{% set version = "1.27.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 5975c20808fa388243f01a8b79021bfbe114f503a27c543f002c5fc8bbdd73dd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - requests >=2.18.4
    - six >=1.11.0
    - typing-extensions >=4.3.0

test:
  imports:
    - azure.core
    - azure.core.pipeline
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
  doc_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
  summary: Microsoft Azure Core Library for Python
  description: |
    Azure core provides shared exceptions and modules for Python SDK client libraries. 
    These libraries follow the Azure SDK Design Guidelines for Python .
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
